### ISSUE TITLE
Register page - different passwords

### ISSUE THREAD

**Issue by liamlawless** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#1]
Summary: You can register an account with the passwords not matching
Description: If you register an account and make the password and the confirm password mismatch, the system will create the account rather than give you an error. You can log in with the original password, not the confirmation password. This does not create any console errors.
Severity: critical/trivial (in between) - It should be easy to fix as this functionality is present in your change password page, however someone may accidentally type their password in wrong and won't ever be able to use the same email address or username again to make an account
Suggestions/Comments:

**Comment by akshatgit** [comment]
@yyt86 FYA
