### ISSUE TITLE
Group page styling changes on empty search

### ISSUE THREAD

**Issue by andrew-bbq** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#10]
Description: When you enter search parameters that don't match any description, everything centers and becomes more narrow.
Severity: Trivial/Cosmetic
Suggestions/Comments: Have a default div there with a set length or something

**Comment by akshatgit** [comment]
Thanks for the suggestion. @Apeksha1999 FYA.

**Comment by akshatgit** [comment]
Solved
