### ISSUE TITLE
Join group button doesn't appear to add user to group

### ISSUE THREAD

**Issue by andrew-bbq** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#11]
Description: When I click the join group button on the groups page, it remains there when I return.
Severity: Critical - users need to join groups
Suggestions/Comments: N/A

**Comment by akshatgit** [comment]
Some code is remaining to be merged with master. @pqu6 FYA

**Comment by pqu6** [comment]
Please pull the newest code, I think it's solved.

**Comment by akshatgit** [comment]
Solved
