### ISSUE TITLE
Filter doesn't work/unclear how it works if it does

### ISSUE THREAD

**Issue by andrew-bbq** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#12]
Description: Filter buttons on groups page don't appear to work (is it meant to be sorting?)
Severity: Trivial+ - can still navigate groups but makes website feel clunky/broken with non-functioning buttons
Suggestions/Comments: N/A

**Comment by akshatgit** [comment]
@Apeksha1999 FYA
