### ISSUE TITLE
Join Button Disappears after Searching

### ISSUE THREAD

**Issue by Aksel-UW** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#13]
Summary: Join Button in the groups section does not show up after searching.
Description: Go to groups section, search for groups (can be empty or with text appearing in at least one group description). Join group button disappears for the groups that fit the query. 
Severity: Major
Suggestions/Comments: If there are many groups, it will be very difficult to join a group if you cannot join after searching. With few groups it is not a big deal since you can just refresh the group page and find the group by scrolling through.

**Comment by akshatgit** [comment]
Thanks for reporting, it is solved now.
