### ISSUE TITLE
Invalid year in Register

### ISSUE THREAD

**Issue by liamlawless** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#2]
Summary: You can enter an invalid year for birthday in the Register Page
Description: You can make your birth year be not only more than the current date but 6 digits long
Severity: Trivial - This probably won't cause any problems, nor would it be likely that someone would enter more than 4 digits for the year.
Suggestions/Comments: This is what the HTML data input allows by default, you can put a max on the date if you like. For example you would add the values to the input element `min="1950-01-01" max="2021-4-21">`

**Comment by akshatgit** [comment]
@yyt86 FYA

**Comment by yyt86** [comment]
solved it by adding some constrain
