### ISSUE TITLE
Nuisance - Registering does not auto log in

### ISSUE THREAD

**Issue by liamlawless** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#3]
Description: Registering for an account takes you to the login page.
Severity: Trivial - This is just a nuisance, not a bug, one can just log in right after signing up.
Suggestions/Comments: Once the user has registered, automatically log them in.

**Comment by akshatgit** [comment]
I have done this purposefully 😅  . Many real-world apps ask you to log in after signup.
