### ISSUE TITLE
Joining private group

### ISSUE THREAD

**Issue by liamlawless** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#4]
Description: Seems to be able to join a group that was created as "private".
Severity: Critical - One should not be able to join a private group of someone else.
Suggestions/Comments:

**Comment by akshatgit** [comment]
@pqu6 FYA

**Comment by pqu6** [comment]
Solved in https://github.com/Apeksha1999/UWStudyCircle-Frontend PR 10.
When join a Private group, will show an alert prompt of "join private group, need admin's approval" and stay on the currant page.
