### ISSUE TITLE
Creating group Private/Public

### ISSUE THREAD

**Issue by liamlawless** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#5]
Summary: One can enter anything for private/public
Description: The public/private part of the form for creating a group allows you to enter any message you like. One can enter something other than public/private (even enter nothing).
Severity: Critical - this can cause your private/public for joining groups to break, because the system won't know whether the group is allowing people to join or not.
Suggestions/Comments: Change the HTML input field to a select/option input field with "public" and "private" as the two options, and make this a required field.

**Comment by akshatgit** [comment]
@yyt86, please work on this issue.

**Comment by yyt86** [comment]
I have fixed it in my branch but haven't merged it into master.
