### ISSUE TITLE
Unclear Profile/Dashboard pages

### ISSUE THREAD

**Issue by liamlawless** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#6]
Description: The Dashboard page is the user's profile and their information. Meanwhile the Profile page is the change password page. It is a little confusing at first.
Severity: Trivial - This is just a UI nuisance, not really a bug.
Suggestions/Comments: Have just one page for Profile (and have the dashboard be something else), and a button on that page to send you to a edit profile page, where you can update the password (and perhaps other values too).

**Comment by akshatgit** [comment]
Thanks for the suggestion. We will try to cover it in our code refactor process.

**Comment by akshatgit** [comment]
We have renamed reset password to settings (earlier named profile page)
