### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by liamlawless** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#7]
Summary: Installation is difficult
Description: Installation requires multiple repositories, and installing many packages and running two things at once through a command line. Non tech-savvy users will have trouble using the application.
Severity: Blocker - This is nuisance but a very important one, the project should not be shipped before this is changed.
Suggestions/Comments: Obviously if you guys had the time to deploy this you would, I understand that you are worrying about the functionality of the project first.

**Comment by andrew-bbq** [comment]
I think this is trivial, the end goal is probably for the group to host it themselves (like what we're currently doing)

**Comment by andrew-bbq** [comment]
I take it back this overly complicated to run

**Comment by akshatgit** [comment]
I'd like to make two points:
1. End-user does not have to install anything. The end-user only needs to go to the frontend app location(wherever it is hosted) and access it via their browser. 
2. @andrew-bbq @liamlawless, please point to steps where it feels complicated. We will try to work on it.

**Comment by andrew-bbq** [comment]
It's just the python virtual environment setup steps are either wrong or different for windows (I had to run ```virtualenvironment``` instead of pip commands and then source files inside of a venv folder instead of whatever you said to do)

**Comment by akshatgit** [comment]
The installation for the backend requirements might differ for windows, but if you have a working virtual env and pip, then the installation is straightforward. We have all the requirements mentioned in the requirements.txt, and our project should run fine once all the dependencies mentioned there are installed. We can only create a docker image to make it easier, but it is not on our radar right now. If you find any dependency not there on requirements.txt, please let us know. We can close this issue if there are no such dependencies.

**Comment by andrew-bbq** [comment]
I'll close it since it's obvious this isn't a user issue, but I think it might be worth mentioning for testing

edit: nvm Liam has to close it since I don't have permissions I don't think.
