### ISSUE TITLE
Login doesn't function on Chrome (or edge)

### ISSUE THREAD

**Issue by andrew-bbq** [UW-Study-Circle/UWStudyCircle--Peer-testing-only-#8]
Description: Even though you recommended Firefox, I initially tested on Chrome. It said that we should use Firefox for full functionality, but it doesn't appear to work at all on Chrome/Edge so maybe just say "Only compatible with Firefox"
Severity: Trivial if you expect users to only use Firefox - Critical if you're expecting wide use since 64% of people use Chrome.
Suggestions/Comments: "Only compatible with Firefox" comment

**Comment by akshatgit** [comment]
We are aware of this issue. There are some new cookies security settings on chrome and currently, we are aiming for the firefox browser only.
